version: '3'
services:
  cashier:
    build: .
    image: tomasbedrich/xcontest-cashier
    restart: always
    volumes:
      - ./cashier:/app/cashier
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
