name: ci

on:
  push:
    branches: master
  pull_request:
    types:
      - closed

jobs:
  build:
    if: ${{ github.ref_name == 'master' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tomasbedrich/xcontest-cashier:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
